bundler_args: --binstubs
language: ruby
notifications:
  irc: "irc.freenode.org#axlsx"
  email:
    recipients:
      - digital.ipseity@gmail.com
      - noel@peden.biz
    on_success: always
env:
  - RAILS_VERSION=4.0
  - RAILS_VERSION=4.1
  - RAILS_VERSION=4.2
rvm:
  - 2.0.0
  - 2.1.1
script:
  spec/ci.rb
