bundler_args: --binstubs
sudo: false
language: ruby
notifications:
  irc: "irc.freenode.org#axlsx"
  email:
    recipients:
      - digital.ipseity@gmail.com
      - noel@peden.biz
    on_success: always
env:
  - RAILS_VERSION=4.0
  - RAILS_VERSION=4.1
  - RAILS_VERSION=4.2
  - RAILS_VERSION=5.0
rvm:
  - 2.1
  - 2.2.2
before_install:
  - gem install bundler
  - bundle
script:
  spec/ci.rb
