bundler_args: --binstubs
language: ruby
notifications:
  irc: "irc.freenode.org#axlsx"
  email:
    recipients:
      - digital.ipseity@gmail.com
      - noel@peden.biz
    on_success: always
env:
  - RAILS_VERSION=3.1
  - RAILS_VERSION=3.2
  - RAILS_VERSION=4.0
rvm:
  - 1.9.3
  - 2.0.0
script:
  - if [[ $RAILS_VERSION == '4.0' ]]; then
  -   cd spec/dummy_4
  - else
  -   cd spec/dummy
  - fi
  - bundle install --without debug
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - cd ../../
  - bundle exec rspec spec
