bundler_args: --binstubs
language: ruby
notifications:
  irc: "irc.freenode.org#axlsx"
  email:
    recipients:
      - digital.ipseity@gmail.com
      - noel@peden.biz
    on_success: always
env:
  - DB=sqlite
rvm:
  - 1.9.3
script:
  spec/ci.sh
